# Please work

on:
  push:
    branches:
      - svelte

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.cf_api_key }}
          accountId: ebad2671db1d8cc9a633d63adb59dd02
          projectName: herremann-er-tilbake-hann
          directory: ./.svelte-kit/cloudflare
          branch: svelte
